version: '3.8'
services:
  backend:
    restart: always
    build:
      context: backend
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD


volumes:
  db:
    driver: local
