version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.3
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

