require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Style
Style/Documentation:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: 'consistent'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

# RSpec
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
RSpec/ImplicitSubject:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'Capfile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'Gemfile'
