# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.1'

gem 'bootsnap', require: false
gem 'devise'
gem 'devise_token_auth'
gem 'dotenv-rails'
gem 'image_processing', '~> 1.2'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.0.4', '>= 7.0.4.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Faster JSON marshalling
gem 'oj'

# https://jsonapi.org/ spec implementation
gem 'jsonapi.rb'
gem 'activerecord-postgis-adapter'
gem 'assignable_values'

## MAYBE INSTALL
# gem "redis", "~> 4.0"
# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

group :development do
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem "rubocop-performance", require: false
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'guard'
  gem 'guard-rspec', require: false
end

group :test do
  gem 'database_cleaner', '~> 1.7.0'
  gem 'rspec-json_expectations'
  gem 'rspec-rails', '~> 6.0.0.rc1'
  gem 'jsonapi-rspec'
  gem 'timecop', '0.9.5'
end
